# fly.toml app configuration file generated for canwemeet-frontend on 2023-11-12T06:59:58-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "canwemeet-frontend"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
